// frontend/src/components/layout/Layout.tsx
import React from 'react';
import { Box } from '@mui/material';
import { Outlet } from 'react-router-dom';
import Header from './Header';
import Footer from './Footer';
import { WhatsAppFloatingButton } from '../common';
import { config } from '../../config';

const Layout: React.FC = () => {
  const whatsappNumber = config.whatsappNumber;

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <Header />
      <Box component="main" sx={{ flexGrow: 1 }}>
        <Outlet />
      </Box>
      <Footer />
      <WhatsAppFloatingButton phoneNumber={whatsappNumber} />
    </Box>
  );
};

export default Layout;

// frontend/src/app/components/layout/layout/layout.component.ts
import { Component } from '@angular/core';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-layout',
  standalone: false,
  template: `
    <div class="app-shell">
      <app-header></app-header>
      <main class="main-content">
        <router-outlet></router-outlet>
      </main>
      <app-footer></app-footer>
      <app-whatsapp-button [phoneNumber]="whatsappNumber"></app-whatsapp-button>
    </div>
  `,
  styles: [`
    .app-shell { display: flex; flex-direction: column; min-height: 100vh; }
    .main-content { flex: 1; }
  `],
})
export class LayoutComponent {
  whatsappNumber = environment.whatsappNumber;
}
