// frontend/src/components/common/ProductCard.tsx
import React from 'react';
import {
  Card,
  CardMedia,
  CardContent,
  CardActions,
  Typography,
  IconButton,
  Button,
  Chip,
  Box,
} from '@mui/material';
import { AddShoppingCart, FavoriteBorder, Favorite } from '@mui/icons-material';
import { Product } from '../../types';

interface ProductCardProps {
  product: Product;
  onAddToCart: (product: Product) => void;
  onToggleFavorite?: (product: Product) => void;
  isFavorite?: boolean;
  imageBaseUrl?: string;
}

const ProductCard: React.FC<ProductCardProps> = ({
  product,
  onAddToCart,
  onToggleFavorite,
  isFavorite = false,
  imageBaseUrl = '/api/public',
}) => {
  const hasOffer = product.offer_price || product.discounted_price;
  const displayPrice = product.offer_price || product.discounted_price || product.selling_price;

  return (
    <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <Box sx={{ position: 'relative' }}>
        <CardMedia
          component="img"
          height="200"
          image={`${imageBaseUrl}/${product.id}/image`}
          alt={product.name}
          sx={{ objectFit: 'cover' }}
        />
        {hasOffer && (
          <Chip
            label={product.offer_name || 'Sale'}
            color="secondary"
            size="small"
            sx={{ position: 'absolute', top: 8, left: 8 }}
          />
        )}
        {onToggleFavorite && (
          <IconButton
            onClick={() => onToggleFavorite(product)}
            sx={{ position: 'absolute', top: 4, right: 4, bgcolor: 'rgba(255,255,255,0.8)' }}
            size="small"
          >
            {isFavorite ? <Favorite color="error" /> : <FavoriteBorder />}
          </IconButton>
        )}
      </Box>
      <CardContent sx={{ flexGrow: 1, pb: 1 }}>
        <Typography gutterBottom variant="subtitle1" component="div" noWrap fontWeight={600}>
          {product.name}
        </Typography>
        <Typography variant="body2" color="text.secondary" noWrap>
          {product.category?.name}
        </Typography>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1 }}>
          <Typography variant="h6" color="primary" fontWeight={700}>
            ₹{displayPrice}
          </Typography>
          {hasOffer && (
            <Typography
              variant="body2"
              color="text.secondary"
              sx={{ textDecoration: 'line-through' }}
            >
              ₹{product.selling_price}
            </Typography>
          )}
        </Box>
      </CardContent>
      <CardActions sx={{ px: 2, pb: 2 }}>
        <Button
          variant="contained"
          size="small"
          startIcon={<AddShoppingCart />}
          onClick={() => onAddToCart(product)}
          fullWidth
        >
          Add to Cart
        </Button>
      </CardActions>
    </Card>
  );
};

export default ProductCard;

// frontend/src/app/components/common/product-card/product-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Product } from '../../../models';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-product-card',
  standalone: false,
  template: `
    <mat-card class="product-card">
      <div class="img-wrapper">
        <img mat-card-image [src]="imageUrl" [alt]="product.name" class="product-img" />
        <mat-chip-set *ngIf="hasOffer" class="offer-badge">
          <mat-chip color="accent" highlighted>{{ product.offer_name || 'Sale' }}</mat-chip>
        </mat-chip-set>
        <button
          *ngIf="showFavorite"
          mat-icon-button
          class="fav-btn"
          (click)="toggleFavorite.emit(product)"
        >
          <mat-icon [color]="isFavorite ? 'warn' : ''">
            {{ isFavorite ? 'favorite' : 'favorite_border' }}
          </mat-icon>
        </button>
      </div>

      <mat-card-content>
        <p class="product-name">{{ product.name }}</p>
        <p class="category-name">{{ product.category?.name }}</p>
        <div class="price-row">
          <span class="price-main">₹{{ displayPrice }}</span>
          <span *ngIf="hasOffer" class="price-original">₹{{ product.selling_price }}</span>
        </div>
      </mat-card-content>

      <mat-card-actions>
        <button mat-raised-button color="primary" class="add-btn" (click)="addToCart.emit(product)">
          <mat-icon>add_shopping_cart</mat-icon>
          Add to Cart
        </button>
      </mat-card-actions>
    </mat-card>
  `,
  styles: [`
    .product-card { height: 100%; display: flex; flex-direction: column; }
    .img-wrapper { position: relative; }
    .product-img { height: 200px; object-fit: cover; width: 100%; }
    .offer-badge { position: absolute; top: 8px; left: 8px; }
    .fav-btn { position: absolute; top: 4px; right: 4px; background: rgba(255,255,255,0.8); }
    mat-card-content { flex: 1; }
    .product-name { font-weight: 600; margin: 8px 0 4px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .category-name { color: #666; font-size: 0.85rem; margin: 0; }
    .price-row { display: flex; align-items: center; gap: 8px; margin-top: 8px; }
    .price-main { font-size: 1.2rem; font-weight: 700; color: #1a237e; }
    .price-original { font-size: 0.9rem; color: #999; text-decoration: line-through; }
    .add-btn { width: 100%; }
    mat-card-actions { padding: 0 16px 16px; }
  `],
})
export class ProductCardComponent {
  @Input() product!: Product;
  @Input() isFavorite = false;
  @Input() showFavorite = false;
  @Output() addToCart = new EventEmitter<Product>();
  @Output() toggleFavorite = new EventEmitter<Product>();

  get hasOffer(): boolean {
    return !!(this.product.offer_price || this.product.discounted_price);
  }

  get displayPrice(): number {
    return this.product.offer_price ?? this.product.discounted_price ?? this.product.selling_price;
  }

  get imageUrl(): string {
    return `${environment.apiUrl}/public/${this.product.id}/image`;
  }
}
